name: Email Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: smtp://rawaan.akhtar@gmail.com:wsbogyalysbjxpwa@smtp.gmail.com:587
        subject: Github Actions job result
        to: rlee3@babson.edu
        from: Ryan Lee <rshlee36@gmail.com>
        body: Build job of ${{github.repository}} completed successfully!t
